# Generated by Django 3.0.2 on 2020-03-20 09:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 20, 9, 35, 31, 593463, tzinfo=utc)),
        ),
    ]
